exp_name: "org_architecture"
model_num: 2 # 1 for base vit architecture and 2 for base vit architecture with RMS norm
details: "base vit architecture with RSM norm" # "base vit architecture" # "base vit architecture with RMS norm"
dataset_name: "cifar10"
seed: 64
batch_size: 64
num_epoch: 100
learning_rate: 3e-4
input_channel: 3
patch_size: 16
# embedding_size: 768
input_image_size: 224
vit_depth: 12
num_class: 100
wandb_project: "vit-small-data"
output_dir: "results"